### ISSUE TITLE
Question: Multiple Days Simulation

### ISSUE THREAD

**Issue by M-Colley** [TUM-VT/sumo_ingolstadt#3]
Hey there, very cool work with the more realistic traffic. 

One question: Will there also be multiple days simulated? As I understand right now, only data for one day is available?

Kind regards

**Comment by behrisch** [comment]
Hi @M-Colley , sorry for the delay. Eventually we will make more days available. Are you rather interested in different weekdays or comparison between different seasons / weather etc.?

**Comment by M-Colley** [comment]
Thank you for your answer! 

Both would be very interesting for me and my research. If I had to choose then different seasons but really, I could use both very well :)

**Comment by behrisch** [comment]
Different days will probably come sooner than different seasons but we will see

**Comment by uhetz** [comment]
I'm also intered in this feature request. What is the status? Are there any ways, I could help you?

**Comment by JoelBrodersen** [comment]
Hello all together,

the calibration framework for a multiple day simulation has been presented with a poster at SUMO User Conference 2024 last week. The corresponding data has now been added to this repository.

Kind regards

Joel
